.ONESHELL:

tgz: \
 15813.tgz \
 15814.tgz \
 15815.tgz \
 158156.tgz \
 158157.tgz 

15815.tgz: 
	tar zcvf $@ $(basename $@)*.dht?

15813.tgz: 
	tar zcvf $@ $(basename $@)*.dht?

15814.tgz: 
	tar zcvf $@ $(basename $@)*.dht?


158156.tgz: 
	tar zcvf $@ $(basename $@)*.dht?

158157.tgz: 
	tar zcvf $@ $(basename $@)*.dht?

FORCE:

